# docker-compose.yml
services:
  development:
    image: ghcr.io/soblin/cpplox-devcontainer:latest
    container_name: cpplox-development-container
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env.example
    command: bash
    tty: true
