# docker-compose.yml
services:
  devcontainer:
    image: ghcr.io/soblin/cpplox-devcontainer:latest
    container_name: cpplox-development-container
    # NOTE: on codespace, "workspaceFolder" command fails to chdir
    # to the specified folder
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
    working_dir: "/workspace"
    env_file:
      - .env.example
    command: bash
    tty: true
