name: dco

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  # this should be the name used in "Require status checks to pass"
  check-dco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Check DCO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -U dco-check
          dco-check --verbose
