# yamllint disable rule:line-length
name: gtest

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # this should be the name used in "Require status checks to pass"
  check-gtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y libboost-all-dev libgtest-dev

      - name: Build
        shell: bash
        env:
          CC: clang
          CXX: clang++
        run: |
          mkdir build
          cd build
          cmake .. -DTRACE_COVERAGE=ON
          make -j

      - name: Run Tests
        shell: bash
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: |
          cd build
          make test

      - name: Measure Coverage
        run: |
          echo ${{ github.workspace }}
          sudo apt-get install lcov llvm
          cd build
          pwd
          lcov -c -d . -o lcov.info --gcov-tool ${{ github.workspace }}/test/llvm-gcov.sh
          lcov --remove lcov.info '/usr/*' --output-file lcov.info

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          file: build/lcov.info
          name: codecov-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
