name: gtest

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  # this should be the name used in "Require status checks to pass"
  check-gtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y libboost-all-dev libgtest-dev

      - name: Build
        shell: bash
        env:
          CC: clang
          CXX: clang++
        run: |
          mkdir build
          cd build
          cmake ..
          make -j

      - name: Run Tests
        shell: bash
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: |
          cd build
          make test
